dist: trusty
language: java
jdk: oraclejdk8
sudo: enabled 
before_install:
    - cd ./thirdPartyJars 
    - ./installJars.sh
    - cd -
install: mvn install -DskipTests -Dgpg.skip
notifications: 
 email:
  recipients: 
   - pawel.trajdos@pwr.edu.pl
  on_success: always
  on_failure: always
        
     
